# Data Structures in Python

# Primitive Data Structures
1. Integers
2. Float
3. Strings
4. Boolean

# Non - Primitive Data Structures
1. Arrays
2. Lists
3. Tupples
4. Dictonaries

# Integers

Integer represent numeric data, and more specifically, whole numbers from negative infinity to infinity, like 4, 5, or -1.

# Float

"Float" stands for 'floating point number'. You can use it for rational numbers, usually ending with a decimal figure, such as 1.11 or 3.14

In [ ]:
#Operations on int and float type

In [1]:
# Floats
x = 4.0
y = 2.0

# Addition
print(x + y)

# Subtraction
print(x - y)

# Multiplication
print(x * y)

# Returns the quotient
print(x / y)

# Returns the remainder
print(x % y) 

# x to the power y
print(x ** y)

6.0
2.0
8.0
2.0
0.0
16.0


# Strings

Strings are collections of alphabets, words or other characters. In Python, you can create strings by enclosing a sequence of characters within a pair of single or double quotes.
Example - 'Hello' or "World"

In [8]:
#Operations in Strings

x = 'Hello'
y = 'World'

#Concatinate two string
print(x + ' ' + y)

#Repeat
print(x*2)

#Slicing
#Range Slicing
a = x[:2]

#Slicing
b = y[0] + y[1]

print(a)
print(b)

x1 = '3'
x2 = '4'

print(x1 + x2)

Hello World
HelloHello
He
Wo
34


In [14]:
#Few helper function for string manupulation

#Capitalize string
print(str.capitalize('hello'))
s = 'hello'
print(s.upper())

#Length of a string
str1 = 'hello world'
print(len(str1))

#Check if string consists only digits
str2 = 'h123'
str3 = '123'

print(str2.isdigit())
print(str3.isdigit())

#replace strings
print(str2.replace('123', 'ello'))


Hello
HELLO
11
False
True
hello


# Boolean

Its a built in data type which can take values of TRUE or FALSE

In [16]:
x = 4
y = 2

print(x == y)

print(x > y)

False
True


# Data type conversion

In [17]:
#To identify data type of a variable we can use built in function type()

a = 2
b = 4.00
c = 'hello'
d = True

print(type(a))
print(type(b))
print(type(c))
print(type(d))

<type 'int'>
<type 'float'>
<type 'str'>
<type 'bool'>


In [ ]:
x = 10
print('Age of X is' + str(x))

In [18]:
x = 2
y = 'hello'

print(x + y)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [6]:
x = 10
print('Age of X is' + str(x))

Age of X is10


In [19]:
x = 2
y = 'hello'

print(str(x) + y)

2hello


# Non Primitive Data Structures

1. Lists
2. Arrays
3. Dictonaries
4. Tupples

# Lists

List is a data structure which we use to store collection of heterogeneous items.
We can initialize a list using square brackets [] which hold the items seperated by comma.

In [1]:
x1 = [] #Empty List
type(x1)

list

In [2]:
x2 = [1, 2, 3]
type(x2)

list

In [3]:
x3 = [1, 'apple', 4]
type(x3)

list

In [7]:
#Accessing data in a list
x4 = ['a', 'b', 'c', 'd']
print(x4[0:3])

['a', 'b', 'c']


In [6]:
#Replacing values
x4[0] = 'z'
print(x4)

['z', 'b', 'c', 'd']


In [7]:
#Common functions for List

#Append
#Append by default adds item to the last index
x = [1, 2, 3, 4, 5]
x.append(6)
x.append(7)
x.append(8)
print(x)

[1, 2, 3, 4, 5, 6]


In [8]:
#Insert
#We can use insert option to insert a value desired index
x = [1, 2, 3, 4, 5]
x.insert(0, 6)
print(x)

[6, 1, 2, 3, 4, 5]


In [11]:
#Remove
x = [1, 2, 3, 4, 5]
x.remove(1)
print(x)

[2, 3, 4, 5]


In [12]:
#reverse
x = [1, 2, 3, 4, 5]
x.reverse()
print(x)

[5, 4, 3, 2, 1]


In [4]:
x = [1, 2, 3, 4, 5]
del x[1]
print(x)

[1, 3, 4, 5]


# Arrays

Arrays is a data structure which we use to store collection of homogenous items.
Numpy Arrays.
NumPy array is a central data structure of the numpy library

In [5]:
import numpy as np

x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [18]:
#Inspecting your array

x = np.array([1, 2, 3, 4, 5])

# Print out the shape 
print(x.shape)

# Print out the data type 
print(x.dtype)

#length of array
print(len(x))

(5,)
int32
5


In [20]:
#Mathematical operations on numpy arrays

a = np.array([2, 4, 6, 8, 10])
b = np.array([3, 6, 9, 12, 15])

print(a-b)          #Subtraction

print(a/2)

print(a == b) #Element wise comparison

print(a.sum())    #Sum on all elements of array
print(a.max())    #Max value
print(a.mean())   #mean of array

[-1 -2 -3 -4 -5]
[1 2 3 4 5]
[False False False False False]
[ True False False False False]
30
10
6.0


# Dictonaries

Dictonaries are a type of data structure which holds a key-value pair.
Key is used to identify the item and Value holds value for that item

In [10]:
a = {'Apple' : 12, 'Banana' : 15, 'Orange' : 20}
print(a)

{'Orange': 20, 'Apple': 25, 'Banana': 15}


In [22]:
#finding value of specific key
print(a['Banana'])

15


In [23]:
#length
print(len(a))

3


In [24]:
#printing keys and values seperately

print(a.keys())
print(a.values())

['Orange', 'Apple', 'Banana']
[20, 12, 15]


In [25]:
#Deleting a key
del a['Banana']
print(a)

{'Orange': 20, 'Apple': 12}


In [7]:
a['Strawberry'] = 24

In [8]:
a

{'Apple': 12, 'Banana': 15, 'Orange': 20, 'Strawberry': 24}

In [9]:
a['Apple'] = 25
a

{'Apple': 25, 'Banana': 15, 'Orange': 20, 'Strawberry': 24}